global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kopitiam-backend'
    static_configs:
      - targets: ['backend:9000']
  - job_name: 'kopitiam-frontend'
    static_configs:
      - targets: ['frontend:3000']
